### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by leonardosnt** [BlackHubOS/EventoZero#7]
```
20:06:02 [GRAVE] Error occurred while enabling EventoZero v1.0.1 (Is it up to date?)
java.lang.NullPointerException
        at br.com.blackhubos.eventozero.factory.EventFactory.loadEvents(EventFactory.java:43)
        at br.com.blackhubos.eventozero.EventoZero.onEnable(EventoZero.java:85)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:282)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:264)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.reload(CraftServer.java:605)
        at org.bukkit.Bukkit.reload(Bukkit.java:275)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:512)
        at net.minecraft.server.v1_5_R3.DedicatedServer.an(DedicatedServer.java:262)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
```

https://github.com/BlackHubOS/EventoZero/blob/master/src/br/com/blackhubos/eventozero/factory/EventFactory.java#L43

**Comment by jhrldev** [comment]
Método listFiles pode retornar nulo, faltou esta verificação!

**Comment by jhrldev** [comment]
Corrigido!
